package com.cjteam.mrile.persistence;

import com.cjteam.mrile.model.DuibaAccount;
import com.cjteam.mrile.model.DuibaAccountExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface DuibaAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    int countByExample(DuibaAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    int deleteByExample(DuibaAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    int insert(DuibaAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    int insertSelective(DuibaAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    List<DuibaAccount> selectByExample(DuibaAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    DuibaAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DuibaAccount record, @Param("example") DuibaAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DuibaAccount record, @Param("example") DuibaAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DuibaAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DuibaAccount record);

    int executeUpdateBySql(Map<String, String> map);

    List<Map<String, Object>> executeSql(Map<String, String> map);
}