package com.cjteam.mrile.model;

import java.io.Serializable;
import java.util.Date;

public class Channel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.group_code
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.code_int
     *
     * @mbggenerated
     */
    private Short codeInt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.used
     *
     * @mbggenerated
     */
    private Byte used;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.max_score_times
     *
     * @mbggenerated
     */
    private Integer maxScoreTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.max_score_daily
     *
     * @mbggenerated
     */
    private Integer maxScoreDaily;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.twice_internal
     *
     * @mbggenerated
     */
    private Integer twiceInternal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.order_
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.is_valid
     *
     * @mbggenerated
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.advertisement_url
     *
     * @mbggenerated
     */
    private String advertisementUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.integral_url
     *
     * @mbggenerated
     */
    private String integralUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.pic
     *
     * @mbggenerated
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.daily_times
     *
     * @mbggenerated
     */
    private Integer dailyTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.platform_sec
     *
     * @mbggenerated
     */
    private String platformSec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.keys
     *
     * @mbggenerated
     */
    private String keys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.package_name
     *
     * @mbggenerated
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table channel
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.id
     *
     * @return the value of channel.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.id
     *
     * @param id the value for channel.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.app_id
     *
     * @return the value of channel.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.app_id
     *
     * @param appId the value for channel.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.group_code
     *
     * @return the value of channel.group_code
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.group_code
     *
     * @param groupCode the value for channel.group_code
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.code
     *
     * @return the value of channel.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.code
     *
     * @param code the value for channel.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.code_int
     *
     * @return the value of channel.code_int
     *
     * @mbggenerated
     */
    public Short getCodeInt() {
        return codeInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.code_int
     *
     * @param codeInt the value for channel.code_int
     *
     * @mbggenerated
     */
    public void setCodeInt(Short codeInt) {
        this.codeInt = codeInt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.used
     *
     * @return the value of channel.used
     *
     * @mbggenerated
     */
    public Byte getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.used
     *
     * @param used the value for channel.used
     *
     * @mbggenerated
     */
    public void setUsed(Byte used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.name
     *
     * @return the value of channel.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.name
     *
     * @param name the value for channel.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.max_score_times
     *
     * @return the value of channel.max_score_times
     *
     * @mbggenerated
     */
    public Integer getMaxScoreTimes() {
        return maxScoreTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.max_score_times
     *
     * @param maxScoreTimes the value for channel.max_score_times
     *
     * @mbggenerated
     */
    public void setMaxScoreTimes(Integer maxScoreTimes) {
        this.maxScoreTimes = maxScoreTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.max_score_daily
     *
     * @return the value of channel.max_score_daily
     *
     * @mbggenerated
     */
    public Integer getMaxScoreDaily() {
        return maxScoreDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.max_score_daily
     *
     * @param maxScoreDaily the value for channel.max_score_daily
     *
     * @mbggenerated
     */
    public void setMaxScoreDaily(Integer maxScoreDaily) {
        this.maxScoreDaily = maxScoreDaily;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.twice_internal
     *
     * @return the value of channel.twice_internal
     *
     * @mbggenerated
     */
    public Integer getTwiceInternal() {
        return twiceInternal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.twice_internal
     *
     * @param twiceInternal the value for channel.twice_internal
     *
     * @mbggenerated
     */
    public void setTwiceInternal(Integer twiceInternal) {
        this.twiceInternal = twiceInternal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.description
     *
     * @return the value of channel.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.description
     *
     * @param description the value for channel.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.order_
     *
     * @return the value of channel.order_
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.order_
     *
     * @param order the value for channel.order_
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.is_valid
     *
     * @return the value of channel.is_valid
     *
     * @mbggenerated
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.is_valid
     *
     * @param isValid the value for channel.is_valid
     *
     * @mbggenerated
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.create_time
     *
     * @return the value of channel.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.create_time
     *
     * @param createTime the value for channel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.update_time
     *
     * @return the value of channel.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.update_time
     *
     * @param updateTime the value for channel.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.advertisement_url
     *
     * @return the value of channel.advertisement_url
     *
     * @mbggenerated
     */
    public String getAdvertisementUrl() {
        return advertisementUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.advertisement_url
     *
     * @param advertisementUrl the value for channel.advertisement_url
     *
     * @mbggenerated
     */
    public void setAdvertisementUrl(String advertisementUrl) {
        this.advertisementUrl = advertisementUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.integral_url
     *
     * @return the value of channel.integral_url
     *
     * @mbggenerated
     */
    public String getIntegralUrl() {
        return integralUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.integral_url
     *
     * @param integralUrl the value for channel.integral_url
     *
     * @mbggenerated
     */
    public void setIntegralUrl(String integralUrl) {
        this.integralUrl = integralUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.type
     *
     * @return the value of channel.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.type
     *
     * @param type the value for channel.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.pic
     *
     * @return the value of channel.pic
     *
     * @mbggenerated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.pic
     *
     * @param pic the value for channel.pic
     *
     * @mbggenerated
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.daily_times
     *
     * @return the value of channel.daily_times
     *
     * @mbggenerated
     */
    public Integer getDailyTimes() {
        return dailyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.daily_times
     *
     * @param dailyTimes the value for channel.daily_times
     *
     * @mbggenerated
     */
    public void setDailyTimes(Integer dailyTimes) {
        this.dailyTimes = dailyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.platform_sec
     *
     * @return the value of channel.platform_sec
     *
     * @mbggenerated
     */
    public String getPlatformSec() {
        return platformSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.platform_sec
     *
     * @param platformSec the value for channel.platform_sec
     *
     * @mbggenerated
     */
    public void setPlatformSec(String platformSec) {
        this.platformSec = platformSec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.keys
     *
     * @return the value of channel.keys
     *
     * @mbggenerated
     */
    public String getKeys() {
        return keys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.keys
     *
     * @param keys the value for channel.keys
     *
     * @mbggenerated
     */
    public void setKeys(String keys) {
        this.keys = keys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.package_name
     *
     * @return the value of channel.package_name
     *
     * @mbggenerated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.package_name
     *
     * @param packageName the value for channel.package_name
     *
     * @mbggenerated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    @Override
    public String toString() {
        return "Channel ["
        + ", id=" + id 
        + ", appId=" + appId 
        + ", groupCode=" + groupCode 
        + ", code=" + code 
        + ", codeInt=" + codeInt 
        + ", used=" + used 
        + ", name=" + name 
        + ", maxScoreTimes=" + maxScoreTimes 
        + ", maxScoreDaily=" + maxScoreDaily 
        + ", twiceInternal=" + twiceInternal 
        + ", description=" + description 
        + ", order=" + order 
        + ", isValid=" + isValid 
        + ", createTime=" + createTime 
        + ", updateTime=" + updateTime 
        + ", advertisementUrl=" + advertisementUrl 
        + ", integralUrl=" + integralUrl 
        + ", type=" + type 
        + ", pic=" + pic 
        + ", dailyTimes=" + dailyTimes 
        + ", platformSec=" + platformSec 
        + ", keys=" + keys 
        + ", packageName=" + packageName 
        + "]";
    }
}