package com.cjteam.mrile.model;

import java.io.Serializable;
import java.util.Date;

public class Integral implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.status
     *
     * @mbggenerated
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.ad_id
     *
     * @mbggenerated
     */
    private String adId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.ad_name
     *
     * @mbggenerated
     */
    private String adName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column integral.udid
     *
     * @mbggenerated
     */
    private String udid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table integral
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.id
     *
     * @return the value of integral.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.id
     *
     * @param id the value for integral.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.app_id
     *
     * @return the value of integral.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.app_id
     *
     * @param appId the value for integral.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.user_id
     *
     * @return the value of integral.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.user_id
     *
     * @param userId the value for integral.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.score
     *
     * @return the value of integral.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.score
     *
     * @param score the value for integral.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.type
     *
     * @return the value of integral.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.type
     *
     * @param type the value for integral.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.channel
     *
     * @return the value of integral.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.channel
     *
     * @param channel the value for integral.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.create_time
     *
     * @return the value of integral.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.create_time
     *
     * @param createTime the value for integral.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.status
     *
     * @return the value of integral.status
     *
     * @mbggenerated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.status
     *
     * @param status the value for integral.status
     *
     * @mbggenerated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.order_id
     *
     * @return the value of integral.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.order_id
     *
     * @param orderId the value for integral.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.ad_id
     *
     * @return the value of integral.ad_id
     *
     * @mbggenerated
     */
    public String getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.ad_id
     *
     * @param adId the value for integral.ad_id
     *
     * @mbggenerated
     */
    public void setAdId(String adId) {
        this.adId = adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.ad_name
     *
     * @return the value of integral.ad_name
     *
     * @mbggenerated
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.ad_name
     *
     * @param adName the value for integral.ad_name
     *
     * @mbggenerated
     */
    public void setAdName(String adName) {
        this.adName = adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.msg
     *
     * @return the value of integral.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.msg
     *
     * @param msg the value for integral.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.ip
     *
     * @return the value of integral.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.ip
     *
     * @param ip the value for integral.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column integral.udid
     *
     * @return the value of integral.udid
     *
     * @mbggenerated
     */
    public String getUdid() {
        return udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column integral.udid
     *
     * @param udid the value for integral.udid
     *
     * @mbggenerated
     */
    public void setUdid(String udid) {
        this.udid = udid;
    }

    @Override
    public String toString() {
        return "Integral ["
        + ", id=" + id 
        + ", appId=" + appId 
        + ", userId=" + userId 
        + ", score=" + score 
        + ", type=" + type 
        + ", channel=" + channel 
        + ", createTime=" + createTime 
        + ", status=" + status 
        + ", orderId=" + orderId 
        + ", adId=" + adId 
        + ", adName=" + adName 
        + ", msg=" + msg 
        + ", ip=" + ip 
        + ", udid=" + udid 
        + "]";
    }
}