package com.cjteam.mrile.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.client_user_id
     *
     * @mbggenerated
     */
    private String clientUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mac
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.open_udid
     *
     * @mbggenerated
     */
    private String openUdid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_phone
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.daily_exchange_limit
     *
     * @mbggenerated
     */
    private String dailyExchangeLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.valid_times
     *
     * @mbggenerated
     */
    private Byte validTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_black
     *
     * @mbggenerated
     */
    private Boolean isBlack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.version_no
     *
     * @mbggenerated
     */
    private String versionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.total_points
     *
     * @mbggenerated
     */
    private Integer totalPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sce
     *
     * @mbggenerated
     */
    private String sce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.surplus
     *
     * @mbggenerated
     */
    private Integer surplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.shark
     *
     * @mbggenerated
     */
    private String shark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.award
     *
     * @mbggenerated
     */
    private Byte award;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.game_score
     *
     * @mbggenerated
     */
    private Integer gameScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.black_cause
     *
     * @mbggenerated
     */
    private String blackCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.alipay_no
     *
     * @mbggenerated
     */
    private String alipayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.version_id
     *
     * @mbggenerated
     */
    private Long versionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.product_time_count
     *
     * @mbggenerated
     */
    private Integer productTimeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.product_eye_count
     *
     * @mbggenerated
     */
    private Integer productEyeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.liveness
     *
     * @mbggenerated
     */
    private Integer liveness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.udid
     *
     * @mbggenerated
     */
    private String udid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.app_id
     *
     * @return the value of user.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.app_id
     *
     * @param appId the value for user.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.client_user_id
     *
     * @return the value of user.client_user_id
     *
     * @mbggenerated
     */
    public String getClientUserId() {
        return clientUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.client_user_id
     *
     * @param clientUserId the value for user.client_user_id
     *
     * @mbggenerated
     */
    public void setClientUserId(String clientUserId) {
        this.clientUserId = clientUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mac
     *
     * @return the value of user.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mac
     *
     * @param mac the value for user.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.open_udid
     *
     * @return the value of user.open_udid
     *
     * @mbggenerated
     */
    public String getOpenUdid() {
        return openUdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.open_udid
     *
     * @param openUdid the value for user.open_udid
     *
     * @mbggenerated
     */
    public void setOpenUdid(String openUdid) {
        this.openUdid = openUdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ip
     *
     * @return the value of user.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ip
     *
     * @param ip the value for user.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.token
     *
     * @return the value of user.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.token
     *
     * @param token the value for user.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile_phone
     *
     * @return the value of user.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile_phone
     *
     * @param mobilePhone the value for user.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.daily_exchange_limit
     *
     * @return the value of user.daily_exchange_limit
     *
     * @mbggenerated
     */
    public String getDailyExchangeLimit() {
        return dailyExchangeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.daily_exchange_limit
     *
     * @param dailyExchangeLimit the value for user.daily_exchange_limit
     *
     * @mbggenerated
     */
    public void setDailyExchangeLimit(String dailyExchangeLimit) {
        this.dailyExchangeLimit = dailyExchangeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.valid_times
     *
     * @return the value of user.valid_times
     *
     * @mbggenerated
     */
    public Byte getValidTimes() {
        return validTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.valid_times
     *
     * @param validTimes the value for user.valid_times
     *
     * @mbggenerated
     */
    public void setValidTimes(Byte validTimes) {
        this.validTimes = validTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_black
     *
     * @return the value of user.is_black
     *
     * @mbggenerated
     */
    public Boolean getIsBlack() {
        return isBlack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_black
     *
     * @param isBlack the value for user.is_black
     *
     * @mbggenerated
     */
    public void setIsBlack(Boolean isBlack) {
        this.isBlack = isBlack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.version_no
     *
     * @return the value of user.version_no
     *
     * @mbggenerated
     */
    public String getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.version_no
     *
     * @param versionNo the value for user.version_no
     *
     * @mbggenerated
     */
    public void setVersionNo(String versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.total_points
     *
     * @return the value of user.total_points
     *
     * @mbggenerated
     */
    public Integer getTotalPoints() {
        return totalPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.total_points
     *
     * @param totalPoints the value for user.total_points
     *
     * @mbggenerated
     */
    public void setTotalPoints(Integer totalPoints) {
        this.totalPoints = totalPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sce
     *
     * @return the value of user.sce
     *
     * @mbggenerated
     */
    public String getSce() {
        return sce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sce
     *
     * @param sce the value for user.sce
     *
     * @mbggenerated
     */
    public void setSce(String sce) {
        this.sce = sce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.surplus
     *
     * @return the value of user.surplus
     *
     * @mbggenerated
     */
    public Integer getSurplus() {
        return surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.surplus
     *
     * @param surplus the value for user.surplus
     *
     * @mbggenerated
     */
    public void setSurplus(Integer surplus) {
        this.surplus = surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.shark
     *
     * @return the value of user.shark
     *
     * @mbggenerated
     */
    public String getShark() {
        return shark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.shark
     *
     * @param shark the value for user.shark
     *
     * @mbggenerated
     */
    public void setShark(String shark) {
        this.shark = shark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.award
     *
     * @return the value of user.award
     *
     * @mbggenerated
     */
    public Byte getAward() {
        return award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.award
     *
     * @param award the value for user.award
     *
     * @mbggenerated
     */
    public void setAward(Byte award) {
        this.award = award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.game_score
     *
     * @return the value of user.game_score
     *
     * @mbggenerated
     */
    public Integer getGameScore() {
        return gameScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.game_score
     *
     * @param gameScore the value for user.game_score
     *
     * @mbggenerated
     */
    public void setGameScore(Integer gameScore) {
        this.gameScore = gameScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.black_cause
     *
     * @return the value of user.black_cause
     *
     * @mbggenerated
     */
    public String getBlackCause() {
        return blackCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.black_cause
     *
     * @param blackCause the value for user.black_cause
     *
     * @mbggenerated
     */
    public void setBlackCause(String blackCause) {
        this.blackCause = blackCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.alipay_no
     *
     * @return the value of user.alipay_no
     *
     * @mbggenerated
     */
    public String getAlipayNo() {
        return alipayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.alipay_no
     *
     * @param alipayNo the value for user.alipay_no
     *
     * @mbggenerated
     */
    public void setAlipayNo(String alipayNo) {
        this.alipayNo = alipayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.version_id
     *
     * @return the value of user.version_id
     *
     * @mbggenerated
     */
    public Long getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.version_id
     *
     * @param versionId the value for user.version_id
     *
     * @mbggenerated
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.product_time_count
     *
     * @return the value of user.product_time_count
     *
     * @mbggenerated
     */
    public Integer getProductTimeCount() {
        return productTimeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.product_time_count
     *
     * @param productTimeCount the value for user.product_time_count
     *
     * @mbggenerated
     */
    public void setProductTimeCount(Integer productTimeCount) {
        this.productTimeCount = productTimeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.product_eye_count
     *
     * @return the value of user.product_eye_count
     *
     * @mbggenerated
     */
    public Integer getProductEyeCount() {
        return productEyeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.product_eye_count
     *
     * @param productEyeCount the value for user.product_eye_count
     *
     * @mbggenerated
     */
    public void setProductEyeCount(Integer productEyeCount) {
        this.productEyeCount = productEyeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.level
     *
     * @return the value of user.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.level
     *
     * @param level the value for user.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.liveness
     *
     * @return the value of user.liveness
     *
     * @mbggenerated
     */
    public Integer getLiveness() {
        return liveness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.liveness
     *
     * @param liveness the value for user.liveness
     *
     * @mbggenerated
     */
    public void setLiveness(Integer liveness) {
        this.liveness = liveness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.udid
     *
     * @return the value of user.udid
     *
     * @mbggenerated
     */
    public String getUdid() {
        return udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.udid
     *
     * @param udid the value for user.udid
     *
     * @mbggenerated
     */
    public void setUdid(String udid) {
        this.udid = udid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_login_time
     *
     * @return the value of user.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_login_time
     *
     * @param lastLoginTime the value for user.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    @Override
    public String toString() {
        return "User ["
        + ", id=" + id 
        + ", appId=" + appId 
        + ", userId=" + userId 
        + ", clientUserId=" + clientUserId 
        + ", mac=" + mac 
        + ", openUdid=" + openUdid 
        + ", ip=" + ip 
        + ", token=" + token 
        + ", nickName=" + nickName 
        + ", password=" + password 
        + ", mobilePhone=" + mobilePhone 
        + ", dailyExchangeLimit=" + dailyExchangeLimit 
        + ", validTimes=" + validTimes 
        + ", isBlack=" + isBlack 
        + ", versionNo=" + versionNo 
        + ", totalPoints=" + totalPoints 
        + ", createTime=" + createTime 
        + ", updateTime=" + updateTime 
        + ", sce=" + sce 
        + ", surplus=" + surplus 
        + ", shark=" + shark 
        + ", award=" + award 
        + ", gameScore=" + gameScore 
        + ", blackCause=" + blackCause 
        + ", alipayNo=" + alipayNo 
        + ", versionId=" + versionId 
        + ", productTimeCount=" + productTimeCount 
        + ", productEyeCount=" + productEyeCount 
        + ", level=" + level 
        + ", qq=" + qq 
        + ", liveness=" + liveness 
        + ", udid=" + udid 
        + ", lastLoginTime=" + lastLoginTime 
        + "]";
    }
}