package com.cjteam.xiao.xiaohua.model;

// Generated 2014-7-23 15:31:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * XiaohuaContent generated by hbm2java
 */
@Entity
@Table(name = "xiaohua_content")
public class XiaohuaContent implements java.io.Serializable {
	public static enum Type{
        image , text ;
    }
    public static enum Field{
        id ,sort ;
    }
	private Integer id;
	private XiaohuaSpiderConfig xiaohuaSpiderConfig;
	private String title;
	private String content;
	private Integer good;
	private Integer bad;
	private String targetId;
	private Date createTime;
	private String pic;
    private String type ;
    private int sort=0 ;
    @Column(name = "sort")
    public int getSort() {
		return sort;
	}
	public void setSort(int sort) {
		this.sort = sort;
	}
    @Column(name = "type")
    public String getType() {
        return type;
    }
    public void setType(String type) {
        this.type = type;
    }
    public XiaohuaContent() {
	}

	public XiaohuaContent(XiaohuaSpiderConfig xiaohuaSpiderConfig,
			String title, String content, Integer good, Integer bad,
			String targetId, Date createTime, String pic) {
		this.xiaohuaSpiderConfig = xiaohuaSpiderConfig;
		this.title = title;
		this.content = content;
		this.good = good;
		this.bad = bad;
		this.targetId = targetId;
		this.createTime = createTime;
		this.pic = pic;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "xiaohua_spider_config_id")
	public XiaohuaSpiderConfig getXiaohuaSpiderConfig() {
		return this.xiaohuaSpiderConfig;
	}

	public void setXiaohuaSpiderConfig(XiaohuaSpiderConfig xiaohuaSpiderConfig) {
		this.xiaohuaSpiderConfig = xiaohuaSpiderConfig;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "good")
	public Integer getGood() {
		return this.good;
	}

	public void setGood(Integer good) {
		this.good = good;
	}

	@Column(name = "bad")
	public Integer getBad() {
		return this.bad;
	}

	public void setBad(Integer bad) {
		this.bad = bad;
	}

	@Column(name = "target_id")
	public String getTargetId() {
		return this.targetId;
	}

	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "pic")
	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

}
