package com.cjteam.xiao.xiaohua.model;

// Generated 2014-7-23 15:31:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * XiaohuaSpiderConfig generated by hbm2java
 */
@Entity
@Table(name = "xiaohua_spider_exception")
public class XiaohuaSpiderException implements java.io.Serializable {
	private Integer id;
	private String url;
    private Date createTime;
    private XiaohuaSpiderConfig xiaohuaSpiderConfig;
	public XiaohuaSpiderException() {
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "xiaohua_spider_config_id")
    public XiaohuaSpiderConfig getXiaohuaSpiderConfig() {
        return this.xiaohuaSpiderConfig;
    }

    public void setXiaohuaSpiderConfig(XiaohuaSpiderConfig xiaohuaSpiderConfig) {
        this.xiaohuaSpiderConfig = xiaohuaSpiderConfig;
    }
}
