/**
 * Copyright © 2015 Beijing ZCOOL Network Technology Co. Ltd.(北京站酷网络科技有限公司). All rights reserved. 
 */
package easyui_springmvc_jpa.aaaaaaaaaaaaaaaaaaaaaaa;

import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.dom.java.Field;
import org.mybatis.generator.internal.DefaultCommentGenerator;

/**
 * @description: TODO
 * @author: Zhang ShiJun
 * @date: Jul 10, 2015 5:58:54 PM
 * 
 */
public class DBCommentGenerator extends DefaultCommentGenerator{
	
	@Override
	public void addFieldComment(Field field,
			IntrospectedTable introspectedTable,
			IntrospectedColumn introspectedColumn) {
		if(introspectedColumn.getRemarks() != null && !"".equals(introspectedColumn.getRemarks())){
			field.addJavaDocLine("/**"); //$NON-NLS-1$
			field.addJavaDocLine(" * This field was generated by MyBatis Generator."); //$NON-NLS-1$
			field.addJavaDocLine(" * " + introspectedColumn.getRemarks());
			//addJavadocTag(field, false);
			field.addJavaDocLine(" */"); //$NON-NLS-1$
		}
    }

}
