package com.cjteam.mrile.persistence;

import com.cjteam.mrile.model.XiaohuaContent;
import com.cjteam.mrile.model.XiaohuaContentExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface XiaohuaContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    int countByExample(XiaohuaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    int deleteByExample(XiaohuaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    int insert(XiaohuaContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    int insertSelective(XiaohuaContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    List<XiaohuaContent> selectByExample(XiaohuaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    XiaohuaContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") XiaohuaContent record, @Param("example") XiaohuaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") XiaohuaContent record, @Param("example") XiaohuaContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(XiaohuaContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaohua_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(XiaohuaContent record);

    int executeUpdateBySql(Map<String, String> map);

    List<Map<String, Object>> executeSql(Map<String, String> map);
}