package com.cjteam.mrile.persistence;

import com.cjteam.mrile.model.AppClient;
import com.cjteam.mrile.model.AppClientExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface AppClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    int countByExample(AppClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    int deleteByExample(AppClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    int insert(AppClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    int insertSelective(AppClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    List<AppClient> selectByExample(AppClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    AppClient selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AppClient record, @Param("example") AppClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AppClient record, @Param("example") AppClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_client
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppClient record);

    int executeUpdateBySql(Map<String, String> map);

    List<Map<String, Object>> executeSql(Map<String, String> map);
}