package com.cjteam.mrile.persistence;

import com.cjteam.mrile.model.DuibaCreditConsume;
import com.cjteam.mrile.model.DuibaCreditConsumeExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

public interface DuibaCreditConsumeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    int countByExample(DuibaCreditConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    int deleteByExample(DuibaCreditConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    int insert(DuibaCreditConsume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    int insertSelective(DuibaCreditConsume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    List<DuibaCreditConsume> selectByExample(DuibaCreditConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    DuibaCreditConsume selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DuibaCreditConsume record, @Param("example") DuibaCreditConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DuibaCreditConsume record, @Param("example") DuibaCreditConsumeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DuibaCreditConsume record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DuibaCreditConsume record);

    int executeUpdateBySql(Map<String, String> map);

    List<Map<String, Object>> executeSql(Map<String, String> map);
}