package com.cjteam.mrile.model;

import java.io.Serializable;

public class AppClient implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.host
     *
     * @mbggenerated
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.update_url
     *
     * @mbggenerated
     */
    private String updateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.about_page
     *
     * @mbggenerated
     */
    private String aboutPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.policy
     *
     * @mbggenerated
     */
    private Byte policy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.help_page
     *
     * @mbggenerated
     */
    private String helpPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_client.notification_type
     *
     * @mbggenerated
     */
    private String notificationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_client
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.id
     *
     * @return the value of app_client.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.id
     *
     * @param id the value for app_client.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.name
     *
     * @return the value of app_client.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.name
     *
     * @param name the value for app_client.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.status
     *
     * @return the value of app_client.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.status
     *
     * @param status the value for app_client.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.desc
     *
     * @return the value of app_client.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.desc
     *
     * @param desc the value for app_client.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.host
     *
     * @return the value of app_client.host
     *
     * @mbggenerated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.host
     *
     * @param host the value for app_client.host
     *
     * @mbggenerated
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.version
     *
     * @return the value of app_client.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.version
     *
     * @param version the value for app_client.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.update_url
     *
     * @return the value of app_client.update_url
     *
     * @mbggenerated
     */
    public String getUpdateUrl() {
        return updateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.update_url
     *
     * @param updateUrl the value for app_client.update_url
     *
     * @mbggenerated
     */
    public void setUpdateUrl(String updateUrl) {
        this.updateUrl = updateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.about_page
     *
     * @return the value of app_client.about_page
     *
     * @mbggenerated
     */
    public String getAboutPage() {
        return aboutPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.about_page
     *
     * @param aboutPage the value for app_client.about_page
     *
     * @mbggenerated
     */
    public void setAboutPage(String aboutPage) {
        this.aboutPage = aboutPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.policy
     *
     * @return the value of app_client.policy
     *
     * @mbggenerated
     */
    public Byte getPolicy() {
        return policy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.policy
     *
     * @param policy the value for app_client.policy
     *
     * @mbggenerated
     */
    public void setPolicy(Byte policy) {
        this.policy = policy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.help_page
     *
     * @return the value of app_client.help_page
     *
     * @mbggenerated
     */
    public String getHelpPage() {
        return helpPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.help_page
     *
     * @param helpPage the value for app_client.help_page
     *
     * @mbggenerated
     */
    public void setHelpPage(String helpPage) {
        this.helpPage = helpPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_client.notification_type
     *
     * @return the value of app_client.notification_type
     *
     * @mbggenerated
     */
    public String getNotificationType() {
        return notificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_client.notification_type
     *
     * @param notificationType the value for app_client.notification_type
     *
     * @mbggenerated
     */
    public void setNotificationType(String notificationType) {
        this.notificationType = notificationType;
    }

    @Override
    public String toString() {
        return "AppClient ["
        + ", id=" + id 
        + ", name=" + name 
        + ", status=" + status 
        + ", desc=" + desc 
        + ", host=" + host 
        + ", version=" + version 
        + ", updateUrl=" + updateUrl 
        + ", aboutPage=" + aboutPage 
        + ", policy=" + policy 
        + ", helpPage=" + helpPage 
        + ", notificationType=" + notificationType 
        + "]";
    }
}