package com.cjteam.mrile.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChannelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table channel
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table channel
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table channel
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    protected String limitClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public ChannelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public String getLimitClause() {
        return limitClause;
    }

    public void setLimitClause(String limitClause) {
        this.limitClause = limitClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table channel
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIsNull() {
            addCriterion("group_code is null");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIsNotNull() {
            addCriterion("group_code is not null");
            return (Criteria) this;
        }

        public Criteria andGroupCodeEqualTo(String value) {
            addCriterion("group_code =", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotEqualTo(String value) {
            addCriterion("group_code <>", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeGreaterThan(String value) {
            addCriterion("group_code >", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeGreaterThanOrEqualTo(String value) {
            addCriterion("group_code >=", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLessThan(String value) {
            addCriterion("group_code <", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLessThanOrEqualTo(String value) {
            addCriterion("group_code <=", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeLike(String value) {
            addCriterion("group_code like", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotLike(String value) {
            addCriterion("group_code not like", value, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeIn(List<String> values) {
            addCriterion("group_code in", values, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotIn(List<String> values) {
            addCriterion("group_code not in", values, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeBetween(String value1, String value2) {
            addCriterion("group_code between", value1, value2, "groupCode");
            return (Criteria) this;
        }

        public Criteria andGroupCodeNotBetween(String value1, String value2) {
            addCriterion("group_code not between", value1, value2, "groupCode");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIntIsNull() {
            addCriterion("code_int is null");
            return (Criteria) this;
        }

        public Criteria andCodeIntIsNotNull() {
            addCriterion("code_int is not null");
            return (Criteria) this;
        }

        public Criteria andCodeIntEqualTo(Short value) {
            addCriterion("code_int =", value, "codeInt");
            return (Criteria) this;
        }

        public Criteria andCodeIntNotEqualTo(Short value) {
            addCriterion("code_int <>", value, "codeInt");
            return (Criteria) this;
        }

        public Criteria andCodeIntGreaterThan(Short value) {
            addCriterion("code_int >", value, "codeInt");
            return (Criteria) this;
        }

        public Criteria andCodeIntGreaterThanOrEqualTo(Short value) {
            addCriterion("code_int >=", value, "codeInt");
            return (Criteria) this;
        }

        public Criteria andCodeIntLessThan(Short value) {
            addCriterion("code_int <", value, "codeInt");
            return (Criteria) this;
        }

        public Criteria andCodeIntLessThanOrEqualTo(Short value) {
            addCriterion("code_int <=", value, "codeInt");
            return (Criteria) this;
        }

        public Criteria andCodeIntIn(List<Short> values) {
            addCriterion("code_int in", values, "codeInt");
            return (Criteria) this;
        }

        public Criteria andCodeIntNotIn(List<Short> values) {
            addCriterion("code_int not in", values, "codeInt");
            return (Criteria) this;
        }

        public Criteria andCodeIntBetween(Short value1, Short value2) {
            addCriterion("code_int between", value1, value2, "codeInt");
            return (Criteria) this;
        }

        public Criteria andCodeIntNotBetween(Short value1, Short value2) {
            addCriterion("code_int not between", value1, value2, "codeInt");
            return (Criteria) this;
        }

        public Criteria andUsedIsNull() {
            addCriterion("used is null");
            return (Criteria) this;
        }

        public Criteria andUsedIsNotNull() {
            addCriterion("used is not null");
            return (Criteria) this;
        }

        public Criteria andUsedEqualTo(Byte value) {
            addCriterion("used =", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedNotEqualTo(Byte value) {
            addCriterion("used <>", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedGreaterThan(Byte value) {
            addCriterion("used >", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedGreaterThanOrEqualTo(Byte value) {
            addCriterion("used >=", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedLessThan(Byte value) {
            addCriterion("used <", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedLessThanOrEqualTo(Byte value) {
            addCriterion("used <=", value, "used");
            return (Criteria) this;
        }

        public Criteria andUsedIn(List<Byte> values) {
            addCriterion("used in", values, "used");
            return (Criteria) this;
        }

        public Criteria andUsedNotIn(List<Byte> values) {
            addCriterion("used not in", values, "used");
            return (Criteria) this;
        }

        public Criteria andUsedBetween(Byte value1, Byte value2) {
            addCriterion("used between", value1, value2, "used");
            return (Criteria) this;
        }

        public Criteria andUsedNotBetween(Byte value1, Byte value2) {
            addCriterion("used not between", value1, value2, "used");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesIsNull() {
            addCriterion("max_score_times is null");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesIsNotNull() {
            addCriterion("max_score_times is not null");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesEqualTo(Integer value) {
            addCriterion("max_score_times =", value, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesNotEqualTo(Integer value) {
            addCriterion("max_score_times <>", value, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesGreaterThan(Integer value) {
            addCriterion("max_score_times >", value, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_score_times >=", value, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesLessThan(Integer value) {
            addCriterion("max_score_times <", value, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesLessThanOrEqualTo(Integer value) {
            addCriterion("max_score_times <=", value, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesIn(List<Integer> values) {
            addCriterion("max_score_times in", values, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesNotIn(List<Integer> values) {
            addCriterion("max_score_times not in", values, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesBetween(Integer value1, Integer value2) {
            addCriterion("max_score_times between", value1, value2, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("max_score_times not between", value1, value2, "maxScoreTimes");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyIsNull() {
            addCriterion("max_score_daily is null");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyIsNotNull() {
            addCriterion("max_score_daily is not null");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyEqualTo(Integer value) {
            addCriterion("max_score_daily =", value, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyNotEqualTo(Integer value) {
            addCriterion("max_score_daily <>", value, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyGreaterThan(Integer value) {
            addCriterion("max_score_daily >", value, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_score_daily >=", value, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyLessThan(Integer value) {
            addCriterion("max_score_daily <", value, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyLessThanOrEqualTo(Integer value) {
            addCriterion("max_score_daily <=", value, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyIn(List<Integer> values) {
            addCriterion("max_score_daily in", values, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyNotIn(List<Integer> values) {
            addCriterion("max_score_daily not in", values, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyBetween(Integer value1, Integer value2) {
            addCriterion("max_score_daily between", value1, value2, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andMaxScoreDailyNotBetween(Integer value1, Integer value2) {
            addCriterion("max_score_daily not between", value1, value2, "maxScoreDaily");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalIsNull() {
            addCriterion("twice_internal is null");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalIsNotNull() {
            addCriterion("twice_internal is not null");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalEqualTo(Integer value) {
            addCriterion("twice_internal =", value, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalNotEqualTo(Integer value) {
            addCriterion("twice_internal <>", value, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalGreaterThan(Integer value) {
            addCriterion("twice_internal >", value, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalGreaterThanOrEqualTo(Integer value) {
            addCriterion("twice_internal >=", value, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalLessThan(Integer value) {
            addCriterion("twice_internal <", value, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalLessThanOrEqualTo(Integer value) {
            addCriterion("twice_internal <=", value, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalIn(List<Integer> values) {
            addCriterion("twice_internal in", values, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalNotIn(List<Integer> values) {
            addCriterion("twice_internal not in", values, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalBetween(Integer value1, Integer value2) {
            addCriterion("twice_internal between", value1, value2, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andTwiceInternalNotBetween(Integer value1, Integer value2) {
            addCriterion("twice_internal not between", value1, value2, "twiceInternal");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andOrderIsNull() {
            addCriterion("order_ is null");
            return (Criteria) this;
        }

        public Criteria andOrderIsNotNull() {
            addCriterion("order_ is not null");
            return (Criteria) this;
        }

        public Criteria andOrderEqualTo(Integer value) {
            addCriterion("order_ =", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotEqualTo(Integer value) {
            addCriterion("order_ <>", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThan(Integer value) {
            addCriterion("order_ >", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_ >=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThan(Integer value) {
            addCriterion("order_ <", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderLessThanOrEqualTo(Integer value) {
            addCriterion("order_ <=", value, "order");
            return (Criteria) this;
        }

        public Criteria andOrderIn(List<Integer> values) {
            addCriterion("order_ in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotIn(List<Integer> values) {
            addCriterion("order_ not in", values, "order");
            return (Criteria) this;
        }

        public Criteria andOrderBetween(Integer value1, Integer value2) {
            addCriterion("order_ between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("order_ not between", value1, value2, "order");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("is_valid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("is_valid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Boolean value) {
            addCriterion("is_valid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Boolean value) {
            addCriterion("is_valid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Boolean value) {
            addCriterion("is_valid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_valid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Boolean value) {
            addCriterion("is_valid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Boolean value) {
            addCriterion("is_valid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Boolean> values) {
            addCriterion("is_valid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Boolean> values) {
            addCriterion("is_valid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Boolean value1, Boolean value2) {
            addCriterion("is_valid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_valid not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlIsNull() {
            addCriterion("advertisement_url is null");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlIsNotNull() {
            addCriterion("advertisement_url is not null");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlEqualTo(String value) {
            addCriterion("advertisement_url =", value, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlNotEqualTo(String value) {
            addCriterion("advertisement_url <>", value, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlGreaterThan(String value) {
            addCriterion("advertisement_url >", value, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlGreaterThanOrEqualTo(String value) {
            addCriterion("advertisement_url >=", value, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlLessThan(String value) {
            addCriterion("advertisement_url <", value, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlLessThanOrEqualTo(String value) {
            addCriterion("advertisement_url <=", value, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlLike(String value) {
            addCriterion("advertisement_url like", value, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlNotLike(String value) {
            addCriterion("advertisement_url not like", value, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlIn(List<String> values) {
            addCriterion("advertisement_url in", values, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlNotIn(List<String> values) {
            addCriterion("advertisement_url not in", values, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlBetween(String value1, String value2) {
            addCriterion("advertisement_url between", value1, value2, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andAdvertisementUrlNotBetween(String value1, String value2) {
            addCriterion("advertisement_url not between", value1, value2, "advertisementUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlIsNull() {
            addCriterion("integral_url is null");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlIsNotNull() {
            addCriterion("integral_url is not null");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlEqualTo(String value) {
            addCriterion("integral_url =", value, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlNotEqualTo(String value) {
            addCriterion("integral_url <>", value, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlGreaterThan(String value) {
            addCriterion("integral_url >", value, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlGreaterThanOrEqualTo(String value) {
            addCriterion("integral_url >=", value, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlLessThan(String value) {
            addCriterion("integral_url <", value, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlLessThanOrEqualTo(String value) {
            addCriterion("integral_url <=", value, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlLike(String value) {
            addCriterion("integral_url like", value, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlNotLike(String value) {
            addCriterion("integral_url not like", value, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlIn(List<String> values) {
            addCriterion("integral_url in", values, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlNotIn(List<String> values) {
            addCriterion("integral_url not in", values, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlBetween(String value1, String value2) {
            addCriterion("integral_url between", value1, value2, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andIntegralUrlNotBetween(String value1, String value2) {
            addCriterion("integral_url not between", value1, value2, "integralUrl");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPicIsNull() {
            addCriterion("pic is null");
            return (Criteria) this;
        }

        public Criteria andPicIsNotNull() {
            addCriterion("pic is not null");
            return (Criteria) this;
        }

        public Criteria andPicEqualTo(String value) {
            addCriterion("pic =", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotEqualTo(String value) {
            addCriterion("pic <>", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicGreaterThan(String value) {
            addCriterion("pic >", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicGreaterThanOrEqualTo(String value) {
            addCriterion("pic >=", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicLessThan(String value) {
            addCriterion("pic <", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicLessThanOrEqualTo(String value) {
            addCriterion("pic <=", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicLike(String value) {
            addCriterion("pic like", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotLike(String value) {
            addCriterion("pic not like", value, "pic");
            return (Criteria) this;
        }

        public Criteria andPicIn(List<String> values) {
            addCriterion("pic in", values, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotIn(List<String> values) {
            addCriterion("pic not in", values, "pic");
            return (Criteria) this;
        }

        public Criteria andPicBetween(String value1, String value2) {
            addCriterion("pic between", value1, value2, "pic");
            return (Criteria) this;
        }

        public Criteria andPicNotBetween(String value1, String value2) {
            addCriterion("pic not between", value1, value2, "pic");
            return (Criteria) this;
        }

        public Criteria andDailyTimesIsNull() {
            addCriterion("daily_times is null");
            return (Criteria) this;
        }

        public Criteria andDailyTimesIsNotNull() {
            addCriterion("daily_times is not null");
            return (Criteria) this;
        }

        public Criteria andDailyTimesEqualTo(Integer value) {
            addCriterion("daily_times =", value, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andDailyTimesNotEqualTo(Integer value) {
            addCriterion("daily_times <>", value, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andDailyTimesGreaterThan(Integer value) {
            addCriterion("daily_times >", value, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andDailyTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("daily_times >=", value, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andDailyTimesLessThan(Integer value) {
            addCriterion("daily_times <", value, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andDailyTimesLessThanOrEqualTo(Integer value) {
            addCriterion("daily_times <=", value, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andDailyTimesIn(List<Integer> values) {
            addCriterion("daily_times in", values, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andDailyTimesNotIn(List<Integer> values) {
            addCriterion("daily_times not in", values, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andDailyTimesBetween(Integer value1, Integer value2) {
            addCriterion("daily_times between", value1, value2, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andDailyTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("daily_times not between", value1, value2, "dailyTimes");
            return (Criteria) this;
        }

        public Criteria andPlatformSecIsNull() {
            addCriterion("platform_sec is null");
            return (Criteria) this;
        }

        public Criteria andPlatformSecIsNotNull() {
            addCriterion("platform_sec is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformSecEqualTo(String value) {
            addCriterion("platform_sec =", value, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecNotEqualTo(String value) {
            addCriterion("platform_sec <>", value, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecGreaterThan(String value) {
            addCriterion("platform_sec >", value, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecGreaterThanOrEqualTo(String value) {
            addCriterion("platform_sec >=", value, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecLessThan(String value) {
            addCriterion("platform_sec <", value, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecLessThanOrEqualTo(String value) {
            addCriterion("platform_sec <=", value, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecLike(String value) {
            addCriterion("platform_sec like", value, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecNotLike(String value) {
            addCriterion("platform_sec not like", value, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecIn(List<String> values) {
            addCriterion("platform_sec in", values, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecNotIn(List<String> values) {
            addCriterion("platform_sec not in", values, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecBetween(String value1, String value2) {
            addCriterion("platform_sec between", value1, value2, "platformSec");
            return (Criteria) this;
        }

        public Criteria andPlatformSecNotBetween(String value1, String value2) {
            addCriterion("platform_sec not between", value1, value2, "platformSec");
            return (Criteria) this;
        }

        public Criteria andKeysIsNull() {
            addCriterion("keys is null");
            return (Criteria) this;
        }

        public Criteria andKeysIsNotNull() {
            addCriterion("keys is not null");
            return (Criteria) this;
        }

        public Criteria andKeysEqualTo(String value) {
            addCriterion("keys =", value, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysNotEqualTo(String value) {
            addCriterion("keys <>", value, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysGreaterThan(String value) {
            addCriterion("keys >", value, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysGreaterThanOrEqualTo(String value) {
            addCriterion("keys >=", value, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysLessThan(String value) {
            addCriterion("keys <", value, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysLessThanOrEqualTo(String value) {
            addCriterion("keys <=", value, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysLike(String value) {
            addCriterion("keys like", value, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysNotLike(String value) {
            addCriterion("keys not like", value, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysIn(List<String> values) {
            addCriterion("keys in", values, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysNotIn(List<String> values) {
            addCriterion("keys not in", values, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysBetween(String value1, String value2) {
            addCriterion("keys between", value1, value2, "keys");
            return (Criteria) this;
        }

        public Criteria andKeysNotBetween(String value1, String value2) {
            addCriterion("keys not between", value1, value2, "keys");
            return (Criteria) this;
        }

        public Criteria andPackageNameIsNull() {
            addCriterion("package_name is null");
            return (Criteria) this;
        }

        public Criteria andPackageNameIsNotNull() {
            addCriterion("package_name is not null");
            return (Criteria) this;
        }

        public Criteria andPackageNameEqualTo(String value) {
            addCriterion("package_name =", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotEqualTo(String value) {
            addCriterion("package_name <>", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThan(String value) {
            addCriterion("package_name >", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameGreaterThanOrEqualTo(String value) {
            addCriterion("package_name >=", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThan(String value) {
            addCriterion("package_name <", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLessThanOrEqualTo(String value) {
            addCriterion("package_name <=", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameLike(String value) {
            addCriterion("package_name like", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotLike(String value) {
            addCriterion("package_name not like", value, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameIn(List<String> values) {
            addCriterion("package_name in", values, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotIn(List<String> values) {
            addCriterion("package_name not in", values, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameBetween(String value1, String value2) {
            addCriterion("package_name between", value1, value2, "packageName");
            return (Criteria) this;
        }

        public Criteria andPackageNameNotBetween(String value1, String value2) {
            addCriterion("package_name not between", value1, value2, "packageName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table channel
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table channel
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}