package com.cjteam.mrile.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DuibaCreditConsumeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    protected String limitClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public DuibaCreditConsumeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public String getLimitClause() {
        return limitClause;
    }

    public void setLimitClause(String limitClause) {
        this.limitClause = limitClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppKeyIsNull() {
            addCriterion("app_key is null");
            return (Criteria) this;
        }

        public Criteria andAppKeyIsNotNull() {
            addCriterion("app_key is not null");
            return (Criteria) this;
        }

        public Criteria andAppKeyEqualTo(String value) {
            addCriterion("app_key =", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotEqualTo(String value) {
            addCriterion("app_key <>", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThan(String value) {
            addCriterion("app_key >", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThanOrEqualTo(String value) {
            addCriterion("app_key >=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThan(String value) {
            addCriterion("app_key <", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThanOrEqualTo(String value) {
            addCriterion("app_key <=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLike(String value) {
            addCriterion("app_key like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotLike(String value) {
            addCriterion("app_key not like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyIn(List<String> values) {
            addCriterion("app_key in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotIn(List<String> values) {
            addCriterion("app_key not in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyBetween(String value1, String value2) {
            addCriterion("app_key between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotBetween(String value1, String value2) {
            addCriterion("app_key not between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andCreditsIsNull() {
            addCriterion("credits is null");
            return (Criteria) this;
        }

        public Criteria andCreditsIsNotNull() {
            addCriterion("credits is not null");
            return (Criteria) this;
        }

        public Criteria andCreditsEqualTo(Integer value) {
            addCriterion("credits =", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsNotEqualTo(Integer value) {
            addCriterion("credits <>", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsGreaterThan(Integer value) {
            addCriterion("credits >", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsGreaterThanOrEqualTo(Integer value) {
            addCriterion("credits >=", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsLessThan(Integer value) {
            addCriterion("credits <", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsLessThanOrEqualTo(Integer value) {
            addCriterion("credits <=", value, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsIn(List<Integer> values) {
            addCriterion("credits in", values, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsNotIn(List<Integer> values) {
            addCriterion("credits not in", values, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsBetween(Integer value1, Integer value2) {
            addCriterion("credits between", value1, value2, "credits");
            return (Criteria) this;
        }

        public Criteria andCreditsNotBetween(Integer value1, Integer value2) {
            addCriterion("credits not between", value1, value2, "credits");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNull() {
            addCriterion("order_num is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNotNull() {
            addCriterion("order_num is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumEqualTo(String value) {
            addCriterion("order_num =", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotEqualTo(String value) {
            addCriterion("order_num <>", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThan(String value) {
            addCriterion("order_num >", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThanOrEqualTo(String value) {
            addCriterion("order_num >=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThan(String value) {
            addCriterion("order_num <", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThanOrEqualTo(String value) {
            addCriterion("order_num <=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLike(String value) {
            addCriterion("order_num like", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotLike(String value) {
            addCriterion("order_num not like", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumIn(List<String> values) {
            addCriterion("order_num in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotIn(List<String> values) {
            addCriterion("order_num not in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumBetween(String value1, String value2) {
            addCriterion("order_num between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotBetween(String value1, String value2) {
            addCriterion("order_num not between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andFacePriceIsNull() {
            addCriterion("face_price is null");
            return (Criteria) this;
        }

        public Criteria andFacePriceIsNotNull() {
            addCriterion("face_price is not null");
            return (Criteria) this;
        }

        public Criteria andFacePriceEqualTo(Integer value) {
            addCriterion("face_price =", value, "facePrice");
            return (Criteria) this;
        }

        public Criteria andFacePriceNotEqualTo(Integer value) {
            addCriterion("face_price <>", value, "facePrice");
            return (Criteria) this;
        }

        public Criteria andFacePriceGreaterThan(Integer value) {
            addCriterion("face_price >", value, "facePrice");
            return (Criteria) this;
        }

        public Criteria andFacePriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("face_price >=", value, "facePrice");
            return (Criteria) this;
        }

        public Criteria andFacePriceLessThan(Integer value) {
            addCriterion("face_price <", value, "facePrice");
            return (Criteria) this;
        }

        public Criteria andFacePriceLessThanOrEqualTo(Integer value) {
            addCriterion("face_price <=", value, "facePrice");
            return (Criteria) this;
        }

        public Criteria andFacePriceIn(List<Integer> values) {
            addCriterion("face_price in", values, "facePrice");
            return (Criteria) this;
        }

        public Criteria andFacePriceNotIn(List<Integer> values) {
            addCriterion("face_price not in", values, "facePrice");
            return (Criteria) this;
        }

        public Criteria andFacePriceBetween(Integer value1, Integer value2) {
            addCriterion("face_price between", value1, value2, "facePrice");
            return (Criteria) this;
        }

        public Criteria andFacePriceNotBetween(Integer value1, Integer value2) {
            addCriterion("face_price not between", value1, value2, "facePrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceIsNull() {
            addCriterion("actual_price is null");
            return (Criteria) this;
        }

        public Criteria andActualPriceIsNotNull() {
            addCriterion("actual_price is not null");
            return (Criteria) this;
        }

        public Criteria andActualPriceEqualTo(Integer value) {
            addCriterion("actual_price =", value, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceNotEqualTo(Integer value) {
            addCriterion("actual_price <>", value, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceGreaterThan(Integer value) {
            addCriterion("actual_price >", value, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("actual_price >=", value, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceLessThan(Integer value) {
            addCriterion("actual_price <", value, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceLessThanOrEqualTo(Integer value) {
            addCriterion("actual_price <=", value, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceIn(List<Integer> values) {
            addCriterion("actual_price in", values, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceNotIn(List<Integer> values) {
            addCriterion("actual_price not in", values, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceBetween(Integer value1, Integer value2) {
            addCriterion("actual_price between", value1, value2, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andActualPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("actual_price not between", value1, value2, "actualPrice");
            return (Criteria) this;
        }

        public Criteria andAlipayIsNull() {
            addCriterion("alipay is null");
            return (Criteria) this;
        }

        public Criteria andAlipayIsNotNull() {
            addCriterion("alipay is not null");
            return (Criteria) this;
        }

        public Criteria andAlipayEqualTo(String value) {
            addCriterion("alipay =", value, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayNotEqualTo(String value) {
            addCriterion("alipay <>", value, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayGreaterThan(String value) {
            addCriterion("alipay >", value, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayGreaterThanOrEqualTo(String value) {
            addCriterion("alipay >=", value, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayLessThan(String value) {
            addCriterion("alipay <", value, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayLessThanOrEqualTo(String value) {
            addCriterion("alipay <=", value, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayLike(String value) {
            addCriterion("alipay like", value, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayNotLike(String value) {
            addCriterion("alipay not like", value, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayIn(List<String> values) {
            addCriterion("alipay in", values, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayNotIn(List<String> values) {
            addCriterion("alipay not in", values, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayBetween(String value1, String value2) {
            addCriterion("alipay between", value1, value2, "alipay");
            return (Criteria) this;
        }

        public Criteria andAlipayNotBetween(String value1, String value2) {
            addCriterion("alipay not between", value1, value2, "alipay");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("qq in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("qq not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andWaitAuditIsNull() {
            addCriterion("wait_audit is null");
            return (Criteria) this;
        }

        public Criteria andWaitAuditIsNotNull() {
            addCriterion("wait_audit is not null");
            return (Criteria) this;
        }

        public Criteria andWaitAuditEqualTo(Byte value) {
            addCriterion("wait_audit =", value, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andWaitAuditNotEqualTo(Byte value) {
            addCriterion("wait_audit <>", value, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andWaitAuditGreaterThan(Byte value) {
            addCriterion("wait_audit >", value, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andWaitAuditGreaterThanOrEqualTo(Byte value) {
            addCriterion("wait_audit >=", value, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andWaitAuditLessThan(Byte value) {
            addCriterion("wait_audit <", value, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andWaitAuditLessThanOrEqualTo(Byte value) {
            addCriterion("wait_audit <=", value, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andWaitAuditIn(List<Byte> values) {
            addCriterion("wait_audit in", values, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andWaitAuditNotIn(List<Byte> values) {
            addCriterion("wait_audit not in", values, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andWaitAuditBetween(Byte value1, Byte value2) {
            addCriterion("wait_audit between", value1, value2, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andWaitAuditNotBetween(Byte value1, Byte value2) {
            addCriterion("wait_audit not between", value1, value2, "waitAudit");
            return (Criteria) this;
        }

        public Criteria andNotifyResultIsNull() {
            addCriterion("notify_result is null");
            return (Criteria) this;
        }

        public Criteria andNotifyResultIsNotNull() {
            addCriterion("notify_result is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyResultEqualTo(Boolean value) {
            addCriterion("notify_result =", value, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyResultNotEqualTo(Boolean value) {
            addCriterion("notify_result <>", value, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyResultGreaterThan(Boolean value) {
            addCriterion("notify_result >", value, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyResultGreaterThanOrEqualTo(Boolean value) {
            addCriterion("notify_result >=", value, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyResultLessThan(Boolean value) {
            addCriterion("notify_result <", value, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyResultLessThanOrEqualTo(Boolean value) {
            addCriterion("notify_result <=", value, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyResultIn(List<Boolean> values) {
            addCriterion("notify_result in", values, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyResultNotIn(List<Boolean> values) {
            addCriterion("notify_result not in", values, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyResultBetween(Boolean value1, Boolean value2) {
            addCriterion("notify_result between", value1, value2, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyResultNotBetween(Boolean value1, Boolean value2) {
            addCriterion("notify_result not between", value1, value2, "notifyResult");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageIsNull() {
            addCriterion("notify_message is null");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageIsNotNull() {
            addCriterion("notify_message is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageEqualTo(String value) {
            addCriterion("notify_message =", value, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageNotEqualTo(String value) {
            addCriterion("notify_message <>", value, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageGreaterThan(String value) {
            addCriterion("notify_message >", value, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageGreaterThanOrEqualTo(String value) {
            addCriterion("notify_message >=", value, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageLessThan(String value) {
            addCriterion("notify_message <", value, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageLessThanOrEqualTo(String value) {
            addCriterion("notify_message <=", value, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageLike(String value) {
            addCriterion("notify_message like", value, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageNotLike(String value) {
            addCriterion("notify_message not like", value, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageIn(List<String> values) {
            addCriterion("notify_message in", values, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageNotIn(List<String> values) {
            addCriterion("notify_message not in", values, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageBetween(String value1, String value2) {
            addCriterion("notify_message between", value1, value2, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyMessageNotBetween(String value1, String value2) {
            addCriterion("notify_message not between", value1, value2, "notifyMessage");
            return (Criteria) this;
        }

        public Criteria andNotifyDateIsNull() {
            addCriterion("notify_date is null");
            return (Criteria) this;
        }

        public Criteria andNotifyDateIsNotNull() {
            addCriterion("notify_date is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyDateEqualTo(Date value) {
            addCriterion("notify_date =", value, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyDateNotEqualTo(Date value) {
            addCriterion("notify_date <>", value, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyDateGreaterThan(Date value) {
            addCriterion("notify_date >", value, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("notify_date >=", value, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyDateLessThan(Date value) {
            addCriterion("notify_date <", value, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyDateLessThanOrEqualTo(Date value) {
            addCriterion("notify_date <=", value, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyDateIn(List<Date> values) {
            addCriterion("notify_date in", values, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyDateNotIn(List<Date> values) {
            addCriterion("notify_date not in", values, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyDateBetween(Date value1, Date value2) {
            addCriterion("notify_date between", value1, value2, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andNotifyDateNotBetween(Date value1, Date value2) {
            addCriterion("notify_date not between", value1, value2, "notifyDate");
            return (Criteria) this;
        }

        public Criteria andConsumeResultIsNull() {
            addCriterion("consume_result is null");
            return (Criteria) this;
        }

        public Criteria andConsumeResultIsNotNull() {
            addCriterion("consume_result is not null");
            return (Criteria) this;
        }

        public Criteria andConsumeResultEqualTo(Boolean value) {
            addCriterion("consume_result =", value, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeResultNotEqualTo(Boolean value) {
            addCriterion("consume_result <>", value, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeResultGreaterThan(Boolean value) {
            addCriterion("consume_result >", value, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeResultGreaterThanOrEqualTo(Boolean value) {
            addCriterion("consume_result >=", value, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeResultLessThan(Boolean value) {
            addCriterion("consume_result <", value, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeResultLessThanOrEqualTo(Boolean value) {
            addCriterion("consume_result <=", value, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeResultIn(List<Boolean> values) {
            addCriterion("consume_result in", values, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeResultNotIn(List<Boolean> values) {
            addCriterion("consume_result not in", values, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeResultBetween(Boolean value1, Boolean value2) {
            addCriterion("consume_result between", value1, value2, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeResultNotBetween(Boolean value1, Boolean value2) {
            addCriterion("consume_result not between", value1, value2, "consumeResult");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageIsNull() {
            addCriterion("consume_message is null");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageIsNotNull() {
            addCriterion("consume_message is not null");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageEqualTo(String value) {
            addCriterion("consume_message =", value, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageNotEqualTo(String value) {
            addCriterion("consume_message <>", value, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageGreaterThan(String value) {
            addCriterion("consume_message >", value, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageGreaterThanOrEqualTo(String value) {
            addCriterion("consume_message >=", value, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageLessThan(String value) {
            addCriterion("consume_message <", value, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageLessThanOrEqualTo(String value) {
            addCriterion("consume_message <=", value, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageLike(String value) {
            addCriterion("consume_message like", value, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageNotLike(String value) {
            addCriterion("consume_message not like", value, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageIn(List<String> values) {
            addCriterion("consume_message in", values, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageNotIn(List<String> values) {
            addCriterion("consume_message not in", values, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageBetween(String value1, String value2) {
            addCriterion("consume_message between", value1, value2, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andConsumeMessageNotBetween(String value1, String value2) {
            addCriterion("consume_message not between", value1, value2, "consumeMessage");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}