package com.cjteam.mrile.model;

import java.io.Serializable;
import java.util.Date;

public class DuibaCreditConsume implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.app_key
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.credits
     *
     * @mbggenerated
     */
    private Integer credits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.order_num
     *
     * @mbggenerated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.face_price
     *
     * @mbggenerated
     */
    private Integer facePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.actual_price
     *
     * @mbggenerated
     */
    private Integer actualPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.alipay
     *
     * @mbggenerated
     */
    private String alipay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.qq
     *
     * @mbggenerated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.wait_audit
     *
     * @mbggenerated
     */
    private Byte waitAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.notify_result
     *
     * @mbggenerated
     */
    private Boolean notifyResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.notify_message
     *
     * @mbggenerated
     */
    private String notifyMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.notify_date
     *
     * @mbggenerated
     */
    private Date notifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.consume_result
     *
     * @mbggenerated
     */
    private Boolean consumeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.consume_message
     *
     * @mbggenerated
     */
    private String consumeMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duiba_credit_consume.timestamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table duiba_credit_consume
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.id
     *
     * @return the value of duiba_credit_consume.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.id
     *
     * @param id the value for duiba_credit_consume.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.app_key
     *
     * @return the value of duiba_credit_consume.app_key
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.app_key
     *
     * @param appKey the value for duiba_credit_consume.app_key
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.credits
     *
     * @return the value of duiba_credit_consume.credits
     *
     * @mbggenerated
     */
    public Integer getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.credits
     *
     * @param credits the value for duiba_credit_consume.credits
     *
     * @mbggenerated
     */
    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.order_num
     *
     * @return the value of duiba_credit_consume.order_num
     *
     * @mbggenerated
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.order_num
     *
     * @param orderNum the value for duiba_credit_consume.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.description
     *
     * @return the value of duiba_credit_consume.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.description
     *
     * @param description the value for duiba_credit_consume.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.type
     *
     * @return the value of duiba_credit_consume.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.type
     *
     * @param type the value for duiba_credit_consume.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.face_price
     *
     * @return the value of duiba_credit_consume.face_price
     *
     * @mbggenerated
     */
    public Integer getFacePrice() {
        return facePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.face_price
     *
     * @param facePrice the value for duiba_credit_consume.face_price
     *
     * @mbggenerated
     */
    public void setFacePrice(Integer facePrice) {
        this.facePrice = facePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.actual_price
     *
     * @return the value of duiba_credit_consume.actual_price
     *
     * @mbggenerated
     */
    public Integer getActualPrice() {
        return actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.actual_price
     *
     * @param actualPrice the value for duiba_credit_consume.actual_price
     *
     * @mbggenerated
     */
    public void setActualPrice(Integer actualPrice) {
        this.actualPrice = actualPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.alipay
     *
     * @return the value of duiba_credit_consume.alipay
     *
     * @mbggenerated
     */
    public String getAlipay() {
        return alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.alipay
     *
     * @param alipay the value for duiba_credit_consume.alipay
     *
     * @mbggenerated
     */
    public void setAlipay(String alipay) {
        this.alipay = alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.phone
     *
     * @return the value of duiba_credit_consume.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.phone
     *
     * @param phone the value for duiba_credit_consume.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.qq
     *
     * @return the value of duiba_credit_consume.qq
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.qq
     *
     * @param qq the value for duiba_credit_consume.qq
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.uid
     *
     * @return the value of duiba_credit_consume.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.uid
     *
     * @param uid the value for duiba_credit_consume.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.wait_audit
     *
     * @return the value of duiba_credit_consume.wait_audit
     *
     * @mbggenerated
     */
    public Byte getWaitAudit() {
        return waitAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.wait_audit
     *
     * @param waitAudit the value for duiba_credit_consume.wait_audit
     *
     * @mbggenerated
     */
    public void setWaitAudit(Byte waitAudit) {
        this.waitAudit = waitAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.notify_result
     *
     * @return the value of duiba_credit_consume.notify_result
     *
     * @mbggenerated
     */
    public Boolean getNotifyResult() {
        return notifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.notify_result
     *
     * @param notifyResult the value for duiba_credit_consume.notify_result
     *
     * @mbggenerated
     */
    public void setNotifyResult(Boolean notifyResult) {
        this.notifyResult = notifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.notify_message
     *
     * @return the value of duiba_credit_consume.notify_message
     *
     * @mbggenerated
     */
    public String getNotifyMessage() {
        return notifyMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.notify_message
     *
     * @param notifyMessage the value for duiba_credit_consume.notify_message
     *
     * @mbggenerated
     */
    public void setNotifyMessage(String notifyMessage) {
        this.notifyMessage = notifyMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.notify_date
     *
     * @return the value of duiba_credit_consume.notify_date
     *
     * @mbggenerated
     */
    public Date getNotifyDate() {
        return notifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.notify_date
     *
     * @param notifyDate the value for duiba_credit_consume.notify_date
     *
     * @mbggenerated
     */
    public void setNotifyDate(Date notifyDate) {
        this.notifyDate = notifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.consume_result
     *
     * @return the value of duiba_credit_consume.consume_result
     *
     * @mbggenerated
     */
    public Boolean getConsumeResult() {
        return consumeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.consume_result
     *
     * @param consumeResult the value for duiba_credit_consume.consume_result
     *
     * @mbggenerated
     */
    public void setConsumeResult(Boolean consumeResult) {
        this.consumeResult = consumeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.consume_message
     *
     * @return the value of duiba_credit_consume.consume_message
     *
     * @mbggenerated
     */
    public String getConsumeMessage() {
        return consumeMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.consume_message
     *
     * @param consumeMessage the value for duiba_credit_consume.consume_message
     *
     * @mbggenerated
     */
    public void setConsumeMessage(String consumeMessage) {
        this.consumeMessage = consumeMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duiba_credit_consume.timestamp
     *
     * @return the value of duiba_credit_consume.timestamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duiba_credit_consume.timestamp
     *
     * @param timestamp the value for duiba_credit_consume.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    @Override
    public String toString() {
        return "DuibaCreditConsume ["
        + ", id=" + id 
        + ", appKey=" + appKey 
        + ", credits=" + credits 
        + ", orderNum=" + orderNum 
        + ", description=" + description 
        + ", type=" + type 
        + ", facePrice=" + facePrice 
        + ", actualPrice=" + actualPrice 
        + ", alipay=" + alipay 
        + ", phone=" + phone 
        + ", qq=" + qq 
        + ", uid=" + uid 
        + ", waitAudit=" + waitAudit 
        + ", notifyResult=" + notifyResult 
        + ", notifyMessage=" + notifyMessage 
        + ", notifyDate=" + notifyDate 
        + ", consumeResult=" + consumeResult 
        + ", consumeMessage=" + consumeMessage 
        + ", timestamp=" + timestamp 
        + "]";
    }
}