package com.cjteam.mrile.model;

import java.io.Serializable;
import java.util.Date;

public class ExchangeRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.surplus
     *
     * @mbggenerated
     */
    private Integer surplus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_record.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exchange_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.id
     *
     * @return the value of exchange_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.id
     *
     * @param id the value for exchange_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.user_id
     *
     * @return the value of exchange_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.user_id
     *
     * @param userId the value for exchange_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.surplus
     *
     * @return the value of exchange_record.surplus
     *
     * @mbggenerated
     */
    public Integer getSurplus() {
        return surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.surplus
     *
     * @param surplus the value for exchange_record.surplus
     *
     * @mbggenerated
     */
    public void setSurplus(Integer surplus) {
        this.surplus = surplus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.content
     *
     * @return the value of exchange_record.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.content
     *
     * @param content the value for exchange_record.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.type
     *
     * @return the value of exchange_record.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.type
     *
     * @param type the value for exchange_record.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_record.create_time
     *
     * @return the value of exchange_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_record.create_time
     *
     * @param createTime the value for exchange_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "ExchangeRecord ["
        + ", id=" + id 
        + ", userId=" + userId 
        + ", surplus=" + surplus 
        + ", content=" + content 
        + ", type=" + type 
        + ", createTime=" + createTime 
        + "]";
    }
}