package com.cjteam.mrile.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    protected String limitClause;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public String getLimitClause() {
        return limitClause;
    }

    public void setLimitClause(String limitClause) {
        this.limitClause = limitClause;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdIsNull() {
            addCriterion("client_user_id is null");
            return (Criteria) this;
        }

        public Criteria andClientUserIdIsNotNull() {
            addCriterion("client_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientUserIdEqualTo(String value) {
            addCriterion("client_user_id =", value, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdNotEqualTo(String value) {
            addCriterion("client_user_id <>", value, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdGreaterThan(String value) {
            addCriterion("client_user_id >", value, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("client_user_id >=", value, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdLessThan(String value) {
            addCriterion("client_user_id <", value, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdLessThanOrEqualTo(String value) {
            addCriterion("client_user_id <=", value, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdLike(String value) {
            addCriterion("client_user_id like", value, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdNotLike(String value) {
            addCriterion("client_user_id not like", value, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdIn(List<String> values) {
            addCriterion("client_user_id in", values, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdNotIn(List<String> values) {
            addCriterion("client_user_id not in", values, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdBetween(String value1, String value2) {
            addCriterion("client_user_id between", value1, value2, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andClientUserIdNotBetween(String value1, String value2) {
            addCriterion("client_user_id not between", value1, value2, "clientUserId");
            return (Criteria) this;
        }

        public Criteria andMacIsNull() {
            addCriterion("mac is null");
            return (Criteria) this;
        }

        public Criteria andMacIsNotNull() {
            addCriterion("mac is not null");
            return (Criteria) this;
        }

        public Criteria andMacEqualTo(String value) {
            addCriterion("mac =", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotEqualTo(String value) {
            addCriterion("mac <>", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacGreaterThan(String value) {
            addCriterion("mac >", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacGreaterThanOrEqualTo(String value) {
            addCriterion("mac >=", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLessThan(String value) {
            addCriterion("mac <", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLessThanOrEqualTo(String value) {
            addCriterion("mac <=", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacLike(String value) {
            addCriterion("mac like", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotLike(String value) {
            addCriterion("mac not like", value, "mac");
            return (Criteria) this;
        }

        public Criteria andMacIn(List<String> values) {
            addCriterion("mac in", values, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotIn(List<String> values) {
            addCriterion("mac not in", values, "mac");
            return (Criteria) this;
        }

        public Criteria andMacBetween(String value1, String value2) {
            addCriterion("mac between", value1, value2, "mac");
            return (Criteria) this;
        }

        public Criteria andMacNotBetween(String value1, String value2) {
            addCriterion("mac not between", value1, value2, "mac");
            return (Criteria) this;
        }

        public Criteria andOpenUdidIsNull() {
            addCriterion("open_udid is null");
            return (Criteria) this;
        }

        public Criteria andOpenUdidIsNotNull() {
            addCriterion("open_udid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenUdidEqualTo(String value) {
            addCriterion("open_udid =", value, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidNotEqualTo(String value) {
            addCriterion("open_udid <>", value, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidGreaterThan(String value) {
            addCriterion("open_udid >", value, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidGreaterThanOrEqualTo(String value) {
            addCriterion("open_udid >=", value, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidLessThan(String value) {
            addCriterion("open_udid <", value, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidLessThanOrEqualTo(String value) {
            addCriterion("open_udid <=", value, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidLike(String value) {
            addCriterion("open_udid like", value, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidNotLike(String value) {
            addCriterion("open_udid not like", value, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidIn(List<String> values) {
            addCriterion("open_udid in", values, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidNotIn(List<String> values) {
            addCriterion("open_udid not in", values, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidBetween(String value1, String value2) {
            addCriterion("open_udid between", value1, value2, "openUdid");
            return (Criteria) this;
        }

        public Criteria andOpenUdidNotBetween(String value1, String value2) {
            addCriterion("open_udid not between", value1, value2, "openUdid");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNull() {
            addCriterion("nick_name is null");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNotNull() {
            addCriterion("nick_name is not null");
            return (Criteria) this;
        }

        public Criteria andNickNameEqualTo(String value) {
            addCriterion("nick_name =", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotEqualTo(String value) {
            addCriterion("nick_name <>", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThan(String value) {
            addCriterion("nick_name >", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("nick_name >=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThan(String value) {
            addCriterion("nick_name <", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThanOrEqualTo(String value) {
            addCriterion("nick_name <=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLike(String value) {
            addCriterion("nick_name like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotLike(String value) {
            addCriterion("nick_name not like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameIn(List<String> values) {
            addCriterion("nick_name in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotIn(List<String> values) {
            addCriterion("nick_name not in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameBetween(String value1, String value2) {
            addCriterion("nick_name between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotBetween(String value1, String value2) {
            addCriterion("nick_name not between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNull() {
            addCriterion("mobile_phone is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("mobile_phone is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneEqualTo(String value) {
            addCriterion("mobile_phone =", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotEqualTo(String value) {
            addCriterion("mobile_phone <>", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThan(String value) {
            addCriterion("mobile_phone >", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_phone >=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThan(String value) {
            addCriterion("mobile_phone <", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("mobile_phone <=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLike(String value) {
            addCriterion("mobile_phone like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotLike(String value) {
            addCriterion("mobile_phone not like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIn(List<String> values) {
            addCriterion("mobile_phone in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotIn(List<String> values) {
            addCriterion("mobile_phone not in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneBetween(String value1, String value2) {
            addCriterion("mobile_phone between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("mobile_phone not between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitIsNull() {
            addCriterion("daily_exchange_limit is null");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitIsNotNull() {
            addCriterion("daily_exchange_limit is not null");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitEqualTo(String value) {
            addCriterion("daily_exchange_limit =", value, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitNotEqualTo(String value) {
            addCriterion("daily_exchange_limit <>", value, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitGreaterThan(String value) {
            addCriterion("daily_exchange_limit >", value, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitGreaterThanOrEqualTo(String value) {
            addCriterion("daily_exchange_limit >=", value, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitLessThan(String value) {
            addCriterion("daily_exchange_limit <", value, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitLessThanOrEqualTo(String value) {
            addCriterion("daily_exchange_limit <=", value, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitLike(String value) {
            addCriterion("daily_exchange_limit like", value, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitNotLike(String value) {
            addCriterion("daily_exchange_limit not like", value, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitIn(List<String> values) {
            addCriterion("daily_exchange_limit in", values, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitNotIn(List<String> values) {
            addCriterion("daily_exchange_limit not in", values, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitBetween(String value1, String value2) {
            addCriterion("daily_exchange_limit between", value1, value2, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andDailyExchangeLimitNotBetween(String value1, String value2) {
            addCriterion("daily_exchange_limit not between", value1, value2, "dailyExchangeLimit");
            return (Criteria) this;
        }

        public Criteria andValidTimesIsNull() {
            addCriterion("valid_times is null");
            return (Criteria) this;
        }

        public Criteria andValidTimesIsNotNull() {
            addCriterion("valid_times is not null");
            return (Criteria) this;
        }

        public Criteria andValidTimesEqualTo(Byte value) {
            addCriterion("valid_times =", value, "validTimes");
            return (Criteria) this;
        }

        public Criteria andValidTimesNotEqualTo(Byte value) {
            addCriterion("valid_times <>", value, "validTimes");
            return (Criteria) this;
        }

        public Criteria andValidTimesGreaterThan(Byte value) {
            addCriterion("valid_times >", value, "validTimes");
            return (Criteria) this;
        }

        public Criteria andValidTimesGreaterThanOrEqualTo(Byte value) {
            addCriterion("valid_times >=", value, "validTimes");
            return (Criteria) this;
        }

        public Criteria andValidTimesLessThan(Byte value) {
            addCriterion("valid_times <", value, "validTimes");
            return (Criteria) this;
        }

        public Criteria andValidTimesLessThanOrEqualTo(Byte value) {
            addCriterion("valid_times <=", value, "validTimes");
            return (Criteria) this;
        }

        public Criteria andValidTimesIn(List<Byte> values) {
            addCriterion("valid_times in", values, "validTimes");
            return (Criteria) this;
        }

        public Criteria andValidTimesNotIn(List<Byte> values) {
            addCriterion("valid_times not in", values, "validTimes");
            return (Criteria) this;
        }

        public Criteria andValidTimesBetween(Byte value1, Byte value2) {
            addCriterion("valid_times between", value1, value2, "validTimes");
            return (Criteria) this;
        }

        public Criteria andValidTimesNotBetween(Byte value1, Byte value2) {
            addCriterion("valid_times not between", value1, value2, "validTimes");
            return (Criteria) this;
        }

        public Criteria andIsBlackIsNull() {
            addCriterion("is_black is null");
            return (Criteria) this;
        }

        public Criteria andIsBlackIsNotNull() {
            addCriterion("is_black is not null");
            return (Criteria) this;
        }

        public Criteria andIsBlackEqualTo(Boolean value) {
            addCriterion("is_black =", value, "isBlack");
            return (Criteria) this;
        }

        public Criteria andIsBlackNotEqualTo(Boolean value) {
            addCriterion("is_black <>", value, "isBlack");
            return (Criteria) this;
        }

        public Criteria andIsBlackGreaterThan(Boolean value) {
            addCriterion("is_black >", value, "isBlack");
            return (Criteria) this;
        }

        public Criteria andIsBlackGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_black >=", value, "isBlack");
            return (Criteria) this;
        }

        public Criteria andIsBlackLessThan(Boolean value) {
            addCriterion("is_black <", value, "isBlack");
            return (Criteria) this;
        }

        public Criteria andIsBlackLessThanOrEqualTo(Boolean value) {
            addCriterion("is_black <=", value, "isBlack");
            return (Criteria) this;
        }

        public Criteria andIsBlackIn(List<Boolean> values) {
            addCriterion("is_black in", values, "isBlack");
            return (Criteria) this;
        }

        public Criteria andIsBlackNotIn(List<Boolean> values) {
            addCriterion("is_black not in", values, "isBlack");
            return (Criteria) this;
        }

        public Criteria andIsBlackBetween(Boolean value1, Boolean value2) {
            addCriterion("is_black between", value1, value2, "isBlack");
            return (Criteria) this;
        }

        public Criteria andIsBlackNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_black not between", value1, value2, "isBlack");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNull() {
            addCriterion("version_no is null");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNotNull() {
            addCriterion("version_no is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNoEqualTo(String value) {
            addCriterion("version_no =", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotEqualTo(String value) {
            addCriterion("version_no <>", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThan(String value) {
            addCriterion("version_no >", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThanOrEqualTo(String value) {
            addCriterion("version_no >=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThan(String value) {
            addCriterion("version_no <", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThanOrEqualTo(String value) {
            addCriterion("version_no <=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLike(String value) {
            addCriterion("version_no like", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotLike(String value) {
            addCriterion("version_no not like", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoIn(List<String> values) {
            addCriterion("version_no in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotIn(List<String> values) {
            addCriterion("version_no not in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoBetween(String value1, String value2) {
            addCriterion("version_no between", value1, value2, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotBetween(String value1, String value2) {
            addCriterion("version_no not between", value1, value2, "versionNo");
            return (Criteria) this;
        }

        public Criteria andTotalPointsIsNull() {
            addCriterion("total_points is null");
            return (Criteria) this;
        }

        public Criteria andTotalPointsIsNotNull() {
            addCriterion("total_points is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPointsEqualTo(Integer value) {
            addCriterion("total_points =", value, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andTotalPointsNotEqualTo(Integer value) {
            addCriterion("total_points <>", value, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andTotalPointsGreaterThan(Integer value) {
            addCriterion("total_points >", value, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andTotalPointsGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_points >=", value, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andTotalPointsLessThan(Integer value) {
            addCriterion("total_points <", value, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andTotalPointsLessThanOrEqualTo(Integer value) {
            addCriterion("total_points <=", value, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andTotalPointsIn(List<Integer> values) {
            addCriterion("total_points in", values, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andTotalPointsNotIn(List<Integer> values) {
            addCriterion("total_points not in", values, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andTotalPointsBetween(Integer value1, Integer value2) {
            addCriterion("total_points between", value1, value2, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andTotalPointsNotBetween(Integer value1, Integer value2) {
            addCriterion("total_points not between", value1, value2, "totalPoints");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSceIsNull() {
            addCriterion("sce is null");
            return (Criteria) this;
        }

        public Criteria andSceIsNotNull() {
            addCriterion("sce is not null");
            return (Criteria) this;
        }

        public Criteria andSceEqualTo(String value) {
            addCriterion("sce =", value, "sce");
            return (Criteria) this;
        }

        public Criteria andSceNotEqualTo(String value) {
            addCriterion("sce <>", value, "sce");
            return (Criteria) this;
        }

        public Criteria andSceGreaterThan(String value) {
            addCriterion("sce >", value, "sce");
            return (Criteria) this;
        }

        public Criteria andSceGreaterThanOrEqualTo(String value) {
            addCriterion("sce >=", value, "sce");
            return (Criteria) this;
        }

        public Criteria andSceLessThan(String value) {
            addCriterion("sce <", value, "sce");
            return (Criteria) this;
        }

        public Criteria andSceLessThanOrEqualTo(String value) {
            addCriterion("sce <=", value, "sce");
            return (Criteria) this;
        }

        public Criteria andSceLike(String value) {
            addCriterion("sce like", value, "sce");
            return (Criteria) this;
        }

        public Criteria andSceNotLike(String value) {
            addCriterion("sce not like", value, "sce");
            return (Criteria) this;
        }

        public Criteria andSceIn(List<String> values) {
            addCriterion("sce in", values, "sce");
            return (Criteria) this;
        }

        public Criteria andSceNotIn(List<String> values) {
            addCriterion("sce not in", values, "sce");
            return (Criteria) this;
        }

        public Criteria andSceBetween(String value1, String value2) {
            addCriterion("sce between", value1, value2, "sce");
            return (Criteria) this;
        }

        public Criteria andSceNotBetween(String value1, String value2) {
            addCriterion("sce not between", value1, value2, "sce");
            return (Criteria) this;
        }

        public Criteria andSurplusIsNull() {
            addCriterion("surplus is null");
            return (Criteria) this;
        }

        public Criteria andSurplusIsNotNull() {
            addCriterion("surplus is not null");
            return (Criteria) this;
        }

        public Criteria andSurplusEqualTo(Integer value) {
            addCriterion("surplus =", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusNotEqualTo(Integer value) {
            addCriterion("surplus <>", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusGreaterThan(Integer value) {
            addCriterion("surplus >", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusGreaterThanOrEqualTo(Integer value) {
            addCriterion("surplus >=", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusLessThan(Integer value) {
            addCriterion("surplus <", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusLessThanOrEqualTo(Integer value) {
            addCriterion("surplus <=", value, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusIn(List<Integer> values) {
            addCriterion("surplus in", values, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusNotIn(List<Integer> values) {
            addCriterion("surplus not in", values, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusBetween(Integer value1, Integer value2) {
            addCriterion("surplus between", value1, value2, "surplus");
            return (Criteria) this;
        }

        public Criteria andSurplusNotBetween(Integer value1, Integer value2) {
            addCriterion("surplus not between", value1, value2, "surplus");
            return (Criteria) this;
        }

        public Criteria andSharkIsNull() {
            addCriterion("shark is null");
            return (Criteria) this;
        }

        public Criteria andSharkIsNotNull() {
            addCriterion("shark is not null");
            return (Criteria) this;
        }

        public Criteria andSharkEqualTo(String value) {
            addCriterion("shark =", value, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkNotEqualTo(String value) {
            addCriterion("shark <>", value, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkGreaterThan(String value) {
            addCriterion("shark >", value, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkGreaterThanOrEqualTo(String value) {
            addCriterion("shark >=", value, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkLessThan(String value) {
            addCriterion("shark <", value, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkLessThanOrEqualTo(String value) {
            addCriterion("shark <=", value, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkLike(String value) {
            addCriterion("shark like", value, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkNotLike(String value) {
            addCriterion("shark not like", value, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkIn(List<String> values) {
            addCriterion("shark in", values, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkNotIn(List<String> values) {
            addCriterion("shark not in", values, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkBetween(String value1, String value2) {
            addCriterion("shark between", value1, value2, "shark");
            return (Criteria) this;
        }

        public Criteria andSharkNotBetween(String value1, String value2) {
            addCriterion("shark not between", value1, value2, "shark");
            return (Criteria) this;
        }

        public Criteria andAwardIsNull() {
            addCriterion("award is null");
            return (Criteria) this;
        }

        public Criteria andAwardIsNotNull() {
            addCriterion("award is not null");
            return (Criteria) this;
        }

        public Criteria andAwardEqualTo(Byte value) {
            addCriterion("award =", value, "award");
            return (Criteria) this;
        }

        public Criteria andAwardNotEqualTo(Byte value) {
            addCriterion("award <>", value, "award");
            return (Criteria) this;
        }

        public Criteria andAwardGreaterThan(Byte value) {
            addCriterion("award >", value, "award");
            return (Criteria) this;
        }

        public Criteria andAwardGreaterThanOrEqualTo(Byte value) {
            addCriterion("award >=", value, "award");
            return (Criteria) this;
        }

        public Criteria andAwardLessThan(Byte value) {
            addCriterion("award <", value, "award");
            return (Criteria) this;
        }

        public Criteria andAwardLessThanOrEqualTo(Byte value) {
            addCriterion("award <=", value, "award");
            return (Criteria) this;
        }

        public Criteria andAwardIn(List<Byte> values) {
            addCriterion("award in", values, "award");
            return (Criteria) this;
        }

        public Criteria andAwardNotIn(List<Byte> values) {
            addCriterion("award not in", values, "award");
            return (Criteria) this;
        }

        public Criteria andAwardBetween(Byte value1, Byte value2) {
            addCriterion("award between", value1, value2, "award");
            return (Criteria) this;
        }

        public Criteria andAwardNotBetween(Byte value1, Byte value2) {
            addCriterion("award not between", value1, value2, "award");
            return (Criteria) this;
        }

        public Criteria andGameScoreIsNull() {
            addCriterion("game_score is null");
            return (Criteria) this;
        }

        public Criteria andGameScoreIsNotNull() {
            addCriterion("game_score is not null");
            return (Criteria) this;
        }

        public Criteria andGameScoreEqualTo(Integer value) {
            addCriterion("game_score =", value, "gameScore");
            return (Criteria) this;
        }

        public Criteria andGameScoreNotEqualTo(Integer value) {
            addCriterion("game_score <>", value, "gameScore");
            return (Criteria) this;
        }

        public Criteria andGameScoreGreaterThan(Integer value) {
            addCriterion("game_score >", value, "gameScore");
            return (Criteria) this;
        }

        public Criteria andGameScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("game_score >=", value, "gameScore");
            return (Criteria) this;
        }

        public Criteria andGameScoreLessThan(Integer value) {
            addCriterion("game_score <", value, "gameScore");
            return (Criteria) this;
        }

        public Criteria andGameScoreLessThanOrEqualTo(Integer value) {
            addCriterion("game_score <=", value, "gameScore");
            return (Criteria) this;
        }

        public Criteria andGameScoreIn(List<Integer> values) {
            addCriterion("game_score in", values, "gameScore");
            return (Criteria) this;
        }

        public Criteria andGameScoreNotIn(List<Integer> values) {
            addCriterion("game_score not in", values, "gameScore");
            return (Criteria) this;
        }

        public Criteria andGameScoreBetween(Integer value1, Integer value2) {
            addCriterion("game_score between", value1, value2, "gameScore");
            return (Criteria) this;
        }

        public Criteria andGameScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("game_score not between", value1, value2, "gameScore");
            return (Criteria) this;
        }

        public Criteria andBlackCauseIsNull() {
            addCriterion("black_cause is null");
            return (Criteria) this;
        }

        public Criteria andBlackCauseIsNotNull() {
            addCriterion("black_cause is not null");
            return (Criteria) this;
        }

        public Criteria andBlackCauseEqualTo(String value) {
            addCriterion("black_cause =", value, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseNotEqualTo(String value) {
            addCriterion("black_cause <>", value, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseGreaterThan(String value) {
            addCriterion("black_cause >", value, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseGreaterThanOrEqualTo(String value) {
            addCriterion("black_cause >=", value, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseLessThan(String value) {
            addCriterion("black_cause <", value, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseLessThanOrEqualTo(String value) {
            addCriterion("black_cause <=", value, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseLike(String value) {
            addCriterion("black_cause like", value, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseNotLike(String value) {
            addCriterion("black_cause not like", value, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseIn(List<String> values) {
            addCriterion("black_cause in", values, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseNotIn(List<String> values) {
            addCriterion("black_cause not in", values, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseBetween(String value1, String value2) {
            addCriterion("black_cause between", value1, value2, "blackCause");
            return (Criteria) this;
        }

        public Criteria andBlackCauseNotBetween(String value1, String value2) {
            addCriterion("black_cause not between", value1, value2, "blackCause");
            return (Criteria) this;
        }

        public Criteria andAlipayNoIsNull() {
            addCriterion("alipay_no is null");
            return (Criteria) this;
        }

        public Criteria andAlipayNoIsNotNull() {
            addCriterion("alipay_no is not null");
            return (Criteria) this;
        }

        public Criteria andAlipayNoEqualTo(String value) {
            addCriterion("alipay_no =", value, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoNotEqualTo(String value) {
            addCriterion("alipay_no <>", value, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoGreaterThan(String value) {
            addCriterion("alipay_no >", value, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoGreaterThanOrEqualTo(String value) {
            addCriterion("alipay_no >=", value, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoLessThan(String value) {
            addCriterion("alipay_no <", value, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoLessThanOrEqualTo(String value) {
            addCriterion("alipay_no <=", value, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoLike(String value) {
            addCriterion("alipay_no like", value, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoNotLike(String value) {
            addCriterion("alipay_no not like", value, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoIn(List<String> values) {
            addCriterion("alipay_no in", values, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoNotIn(List<String> values) {
            addCriterion("alipay_no not in", values, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoBetween(String value1, String value2) {
            addCriterion("alipay_no between", value1, value2, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andAlipayNoNotBetween(String value1, String value2) {
            addCriterion("alipay_no not between", value1, value2, "alipayNo");
            return (Criteria) this;
        }

        public Criteria andVersionIdIsNull() {
            addCriterion("version_id is null");
            return (Criteria) this;
        }

        public Criteria andVersionIdIsNotNull() {
            addCriterion("version_id is not null");
            return (Criteria) this;
        }

        public Criteria andVersionIdEqualTo(Long value) {
            addCriterion("version_id =", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotEqualTo(Long value) {
            addCriterion("version_id <>", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdGreaterThan(Long value) {
            addCriterion("version_id >", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("version_id >=", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLessThan(Long value) {
            addCriterion("version_id <", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdLessThanOrEqualTo(Long value) {
            addCriterion("version_id <=", value, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdIn(List<Long> values) {
            addCriterion("version_id in", values, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotIn(List<Long> values) {
            addCriterion("version_id not in", values, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdBetween(Long value1, Long value2) {
            addCriterion("version_id between", value1, value2, "versionId");
            return (Criteria) this;
        }

        public Criteria andVersionIdNotBetween(Long value1, Long value2) {
            addCriterion("version_id not between", value1, value2, "versionId");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountIsNull() {
            addCriterion("product_time_count is null");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountIsNotNull() {
            addCriterion("product_time_count is not null");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountEqualTo(Integer value) {
            addCriterion("product_time_count =", value, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountNotEqualTo(Integer value) {
            addCriterion("product_time_count <>", value, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountGreaterThan(Integer value) {
            addCriterion("product_time_count >", value, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_time_count >=", value, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountLessThan(Integer value) {
            addCriterion("product_time_count <", value, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountLessThanOrEqualTo(Integer value) {
            addCriterion("product_time_count <=", value, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountIn(List<Integer> values) {
            addCriterion("product_time_count in", values, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountNotIn(List<Integer> values) {
            addCriterion("product_time_count not in", values, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountBetween(Integer value1, Integer value2) {
            addCriterion("product_time_count between", value1, value2, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductTimeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("product_time_count not between", value1, value2, "productTimeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountIsNull() {
            addCriterion("product_eye_count is null");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountIsNotNull() {
            addCriterion("product_eye_count is not null");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountEqualTo(Integer value) {
            addCriterion("product_eye_count =", value, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountNotEqualTo(Integer value) {
            addCriterion("product_eye_count <>", value, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountGreaterThan(Integer value) {
            addCriterion("product_eye_count >", value, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_eye_count >=", value, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountLessThan(Integer value) {
            addCriterion("product_eye_count <", value, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountLessThanOrEqualTo(Integer value) {
            addCriterion("product_eye_count <=", value, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountIn(List<Integer> values) {
            addCriterion("product_eye_count in", values, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountNotIn(List<Integer> values) {
            addCriterion("product_eye_count not in", values, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountBetween(Integer value1, Integer value2) {
            addCriterion("product_eye_count between", value1, value2, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andProductEyeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("product_eye_count not between", value1, value2, "productEyeCount");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("qq is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("qq is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("qq =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("qq <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("qq >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("qq >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("qq <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("qq <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("qq like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("qq not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("qq in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("qq not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("qq between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("qq not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andLivenessIsNull() {
            addCriterion("liveness is null");
            return (Criteria) this;
        }

        public Criteria andLivenessIsNotNull() {
            addCriterion("liveness is not null");
            return (Criteria) this;
        }

        public Criteria andLivenessEqualTo(Integer value) {
            addCriterion("liveness =", value, "liveness");
            return (Criteria) this;
        }

        public Criteria andLivenessNotEqualTo(Integer value) {
            addCriterion("liveness <>", value, "liveness");
            return (Criteria) this;
        }

        public Criteria andLivenessGreaterThan(Integer value) {
            addCriterion("liveness >", value, "liveness");
            return (Criteria) this;
        }

        public Criteria andLivenessGreaterThanOrEqualTo(Integer value) {
            addCriterion("liveness >=", value, "liveness");
            return (Criteria) this;
        }

        public Criteria andLivenessLessThan(Integer value) {
            addCriterion("liveness <", value, "liveness");
            return (Criteria) this;
        }

        public Criteria andLivenessLessThanOrEqualTo(Integer value) {
            addCriterion("liveness <=", value, "liveness");
            return (Criteria) this;
        }

        public Criteria andLivenessIn(List<Integer> values) {
            addCriterion("liveness in", values, "liveness");
            return (Criteria) this;
        }

        public Criteria andLivenessNotIn(List<Integer> values) {
            addCriterion("liveness not in", values, "liveness");
            return (Criteria) this;
        }

        public Criteria andLivenessBetween(Integer value1, Integer value2) {
            addCriterion("liveness between", value1, value2, "liveness");
            return (Criteria) this;
        }

        public Criteria andLivenessNotBetween(Integer value1, Integer value2) {
            addCriterion("liveness not between", value1, value2, "liveness");
            return (Criteria) this;
        }

        public Criteria andUdidIsNull() {
            addCriterion("udid is null");
            return (Criteria) this;
        }

        public Criteria andUdidIsNotNull() {
            addCriterion("udid is not null");
            return (Criteria) this;
        }

        public Criteria andUdidEqualTo(String value) {
            addCriterion("udid =", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidNotEqualTo(String value) {
            addCriterion("udid <>", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidGreaterThan(String value) {
            addCriterion("udid >", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidGreaterThanOrEqualTo(String value) {
            addCriterion("udid >=", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidLessThan(String value) {
            addCriterion("udid <", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidLessThanOrEqualTo(String value) {
            addCriterion("udid <=", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidLike(String value) {
            addCriterion("udid like", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidNotLike(String value) {
            addCriterion("udid not like", value, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidIn(List<String> values) {
            addCriterion("udid in", values, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidNotIn(List<String> values) {
            addCriterion("udid not in", values, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidBetween(String value1, String value2) {
            addCriterion("udid between", value1, value2, "udid");
            return (Criteria) this;
        }

        public Criteria andUdidNotBetween(String value1, String value2) {
            addCriterion("udid not between", value1, value2, "udid");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("last_login_time is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("last_login_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("last_login_time =", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("last_login_time <>", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("last_login_time >", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login_time >=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("last_login_time <", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_login_time <=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIn(List<Date> values) {
            addCriterion("last_login_time in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotIn(List<Date> values) {
            addCriterion("last_login_time not in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("last_login_time between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_login_time not between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}